-- Wrap auth.uid() in RLS policy predicates in (SELECT ...) so Postgres evaluates it once
-- per statement (InitPlan) instead of once per row -- the Supabase-documented RLS perf
-- pattern. Predicate-equivalent (row visibility unchanged). Generated by
-- 'pgrls fix --rule PERF001' and verified (PERF001 -> 0). Refs #50.

-- [PERF001] Wrap auth function call(s) in policy 'Share managers can update requests' on public.access_requests so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Share managers can update requests" ON public.access_requests
    USING (can_manage_shares((SELECT auth.uid()), resource_type, resource_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own requests or requests they manage' on public.access_requests so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own requests or requests they manage" ON public.access_requests
    USING (requester_id = (SELECT auth.uid()) OR can_manage_shares((SELECT auth.uid()), resource_type, resource_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete their own conversations' on public.agent_conversations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete their own conversations" ON public.agent_conversations
    USING (created_by = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'builder_projects_delete' on public.builder_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY builder_projects_delete ON public.builder_projects
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'builder_projects_select' on public.builder_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY builder_projects_select ON public.builder_projects
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'builder_projects_update' on public.builder_projects so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY builder_projects_update ON public.builder_projects
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Channel members can view members' on public.channel_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Channel members can view members" ON public.channel_members
    USING (can_access_channel(channel_id, (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Channel owners can remove members' on public.channel_members so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Channel owners can remove members" ON public.channel_members
    USING (user_id = (SELECT auth.uid()) OR EXISTS (SELECT 1 FROM channel_members AS cm WHERE cm.channel_id = channel_members.channel_id AND cm.user_id = auth.uid() AND cm.role = ANY(ARRAY[CAST('owner' AS text), CAST('moderator' AS text)])));

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete their own read status' on public.channel_read_status so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete their own read status" ON public.channel_read_status
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can modify their own read status' on public.channel_read_status so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can modify their own read status" ON public.channel_read_status
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view their own read status' on public.channel_read_status so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view their own read status" ON public.channel_read_status
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Channel creators can delete channels' on public.channels so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Channel creators can delete channels" ON public.channels
    USING (created_by = (SELECT auth.uid()) OR is_workspace_admin((SELECT workspace_apps.workspace_id FROM workspace_apps WHERE workspace_apps.id = channels.workspace_app_id), (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Channel creators can update channels' on public.channels so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Channel creators can update channels" ON public.channels
    USING (created_by = (SELECT auth.uid()) OR is_workspace_admin((SELECT workspace_apps.workspace_id FROM workspace_apps WHERE workspace_apps.id = channels.workspace_app_id), (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view accessible channels' on public.channels so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view accessible channels" ON public.channels
    USING (can_access_workspace_app(workspace_app_id, (SELECT auth.uid())) AND ((is_dm = FALSE AND is_private = FALSE) OR (is_private = TRUE AND is_dm = FALSE AND (created_by = (SELECT auth.uid()) OR EXISTS (SELECT 1 FROM channel_members WHERE channel_members.channel_id = channels.id AND channel_members.user_id = auth.uid()))) OR (is_dm = TRUE AND (SELECT auth.uid()) = ANY(dm_participants))));

-- [PERF001] Wrap auth function call(s) in policy 'Users can delete their own attachments' on public.chat_attachments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can delete their own attachments" ON public.chat_attachments
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update their own attachments' on public.chat_attachments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update their own attachments" ON public.chat_attachments
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view their own attachments' on public.chat_attachments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view their own attachments" ON public.chat_attachments
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Owner or admin can delete files' on public.files so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Owner or admin can delete files" ON public.files
    USING ((SELECT auth.uid()) = user_id OR (workspace_id IS NOT NULL AND is_workspace_admin(workspace_id)));

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own relationships' on public.memory_relationships so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own relationships" ON public.memory_relationships
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own relationships' on public.memory_relationships so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own relationships" ON public.memory_relationships
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can remove their own reactions' on public.message_reactions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can remove their own reactions" ON public.message_reactions
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Users can manage own preferences' on public.notification_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can manage own preferences" ON public.notification_preferences
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can manage own subscriptions' on public.notification_subscriptions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can manage own subscriptions" ON public.notification_subscriptions
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can read own subscriptions' on public.notification_subscriptions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can read own subscriptions" ON public.notification_subscriptions
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can read own notifications' on public.notifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can read own notifications" ON public.notifications
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own notifications' on public.notifications so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own notifications" ON public.notifications
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Share managers can delete permissions' on public.permissions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Share managers can delete permissions" ON public.permissions
    USING (can_manage_shares((SELECT auth.uid()), resource_type, resource_id));

-- [PERF001] Wrap auth function call(s) in policy 'Share managers can update permissions' on public.permissions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Share managers can update permissions" ON public.permissions
    USING (can_manage_shares((SELECT auth.uid()), resource_type, resource_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can view permissions they manage or own grants' on public.permissions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view permissions they manage or own grants" ON public.permissions
    USING (can_manage_shares((SELECT auth.uid()), resource_type, resource_id) OR (grantee_type = CAST('user' AS text) AND grantee_id = (SELECT auth.uid())));

-- [PERF001] Wrap auth function call(s) in policy 'Creator or admin can delete boards' on public.project_boards so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Creator or admin can delete boards" ON public.project_boards
    USING (created_by = (SELECT auth.uid()) OR is_workspace_admin(workspace_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can remove their own comment reactions' on public.project_comment_reactions so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can remove their own comment reactions" ON public.project_comment_reactions
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Author or admin can delete comments' on public.project_issue_comments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Author or admin can delete comments" ON public.project_issue_comments
    USING (user_id = (SELECT auth.uid()) OR is_workspace_admin(workspace_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can edit their own comments' on public.project_issue_comments so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can edit their own comments" ON public.project_issue_comments
    USING (user_id = (SELECT auth.uid()));

-- [PERF001] Wrap auth function call(s) in policy 'Creator or admin can delete issues' on public.project_issues so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Creator or admin can delete issues" ON public.project_issues
    USING (created_by = (SELECT auth.uid()) OR is_workspace_admin(workspace_id));

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own memory' on public.user_memory so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own memory" ON public.user_memory
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own memory' on public.user_memory so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own memory" ON public.user_memory
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can update own preferences' on public.user_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can update own preferences" ON public.user_preferences
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Users can view own preferences' on public.user_preferences so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Users can view own preferences" ON public.user_preferences
    USING ((SELECT auth.uid()) = user_id);

-- [PERF001] Wrap auth function call(s) in policy 'Service role can manage workspace invitations' on public.workspace_invitations so Postgres can cache the result for the whole statement instead of re-evaluating per row.
ALTER POLICY "Service role can manage workspace invitations" ON public.workspace_invitations
    USING ((SELECT auth.role()) = CAST('service_role' AS text));

-- Also wrap auth.uid() in the WITH CHECK clauses (the USING wraps were in the prior migration;
-- pgrls fix --rule PERF001 only rewrote USING). Predicate-equivalent. Refs #50.

ALTER POLICY "Users can create access requests" ON public.access_requests
    WITH CHECK ((requester_id = (select auth.uid())));

ALTER POLICY "Users can create conversations in their workspaces" ON public.agent_conversations
    WITH CHECK (((workspace_id IN ( SELECT wm.workspace_id FROM workspace_members wm WHERE (wm.user_id = (select auth.uid())))) AND (created_by = (select auth.uid()))));

ALTER POLICY "Workspace admins can insert agents" ON public.agent_instances
    WITH CHECK ((workspace_id IN ( SELECT wm.workspace_id FROM workspace_members wm WHERE ((wm.user_id = (select auth.uid())) AND (wm.role = ANY (ARRAY['owner'::workspace_role, 'admin'::workspace_role]))))));

ALTER POLICY "Users can create tasks in their workspaces" ON public.agent_tasks
    WITH CHECK ((workspace_id IN ( SELECT wm.workspace_id FROM workspace_members wm WHERE (wm.user_id = (select auth.uid())))));

ALTER POLICY "builder_conversations_insert" ON public.builder_conversations
    WITH CHECK ((EXISTS ( SELECT 1 FROM builder_projects WHERE ((builder_projects.id = builder_conversations.project_id) AND (builder_projects.user_id = (select auth.uid()))))));

ALTER POLICY "builder_deployments_insert" ON public.builder_deployments
    WITH CHECK ((EXISTS ( SELECT 1 FROM builder_projects WHERE ((builder_projects.id = builder_deployments.project_id) AND (builder_projects.user_id = (select auth.uid()))))));

ALTER POLICY "builder_messages_insert" ON public.builder_messages
    WITH CHECK ((EXISTS ( SELECT 1 FROM (builder_conversations bc JOIN builder_projects bp ON ((bp.id = bc.project_id))) WHERE ((bc.id = builder_messages.conversation_id) AND (bp.user_id = (select auth.uid()))))));

ALTER POLICY "builder_projects_insert" ON public.builder_projects
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "builder_versions_insert" ON public.builder_versions
    WITH CHECK ((EXISTS ( SELECT 1 FROM builder_projects WHERE ((builder_projects.id = builder_versions.project_id) AND (builder_projects.user_id = (select auth.uid()))))));

ALTER POLICY "Channel owners can add members" ON public.channel_members
    WITH CHECK (((EXISTS ( SELECT 1 FROM channel_members cm WHERE ((cm.channel_id = channel_members.channel_id) AND (cm.user_id = (select auth.uid())) AND (cm.role = ANY (ARRAY['owner'::text, 'moderator'::text]))))) OR (EXISTS ( SELECT 1 FROM channels c WHERE ((c.id = channel_members.channel_id) AND (c.created_by = (select auth.uid())))))));

ALTER POLICY "Users can update their own read status" ON public.channel_read_status
    WITH CHECK ((user_id = (select auth.uid())));

ALTER POLICY "Workspace members can create channels" ON public.channels
    WITH CHECK ((can_access_workspace_app(workspace_app_id, (select auth.uid())) AND (created_by = (select auth.uid()))));

ALTER POLICY "Users can insert their own attachments" ON public.chat_attachments
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can insert their own conversations" ON public.conversations
    WITH CHECK ((( SELECT (select auth.uid()) AS uid) = user_id));

ALTER POLICY "Users can upload files in accessible workspaces" ON public.files
    WITH CHECK ((((select auth.uid()) = user_id) AND ((workspace_app_id IS NULL) OR can_access_workspace_app(workspace_app_id))));

ALTER POLICY "Users can insert own relationships" ON public.memory_relationships
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can insert messages to their conversations" ON public.messages
    WITH CHECK ((EXISTS ( SELECT 1 FROM conversations WHERE ((conversations.id = messages.conversation_id) AND (conversations.user_id = ( SELECT (select auth.uid()) AS uid))))));

ALTER POLICY "Users can manage own preferences" ON public.notification_preferences
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can manage own subscriptions" ON public.notification_subscriptions
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can update own notifications" ON public.notifications
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Share managers can create permissions" ON public.permissions
    WITH CHECK (can_manage_shares((select auth.uid()), resource_type, resource_id));

ALTER POLICY "Members can create boards in accessible workspace apps" ON public.project_boards
    WITH CHECK ((can_access_workspace_app(workspace_app_id) AND ((created_by IS NULL) OR (created_by = (select auth.uid())))));

ALTER POLICY "Members can add comment reactions" ON public.project_comment_reactions
    WITH CHECK ((can_access_workspace_app(workspace_app_id) AND (user_id = (select auth.uid()))));

ALTER POLICY "Members can create comments in accessible workspace apps" ON public.project_issue_comments
    WITH CHECK ((can_access_workspace_app(workspace_app_id) AND (user_id = (select auth.uid()))));

ALTER POLICY "Members can create issues in accessible workspace apps" ON public.project_issues
    WITH CHECK ((can_access_workspace_app(workspace_app_id) AND (created_by = (select auth.uid()))));

ALTER POLICY "Users can insert own memory" ON public.user_memory
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can insert own preferences" ON public.user_preferences
    WITH CHECK (((select auth.uid()) = user_id));

ALTER POLICY "Users can insert own data" ON public.users
    WITH CHECK ((( SELECT (select auth.uid()) AS uid) = id));

ALTER POLICY "Service role can manage workspace invitations" ON public.workspace_invitations
    WITH CHECK (((select auth.role()) = 'service_role'::text));

ALTER POLICY "Users can create workspaces" ON public.workspaces
    WITH CHECK (((select auth.uid()) = owner_id));

